#!/bin/bash

[ -n "`which gdb-multiarch`" ] && gdb="gdb-multiarch" || gdb="arm-none-eabi-gdb"

echo [Calling Make...]
make
echo [Starting QEMU...]
port=$[ $RANDOM % 1024 + 1024 ]
qemu-arm -cpu cortex-m4 -g $port build/firmware.elf &
qemu_pid=$!
echo [Starting GDB...]
[ -f .gdb ] && commands_file_option="-x .gdb"
$gdb build/firmware.elf -ex 'target remote localhost:'$port -ex 'b End_Main' $commands_file_option
kill $qemu_pid
